export const config = {
  apiBase: '/api',
  profileKey: 'kmu.profile',
  sessionKey: 'kmu.session',
  timeZone: 'Asia/Seoul',
  categories: [
    '학사',
    '장학',
    '공모전·행사',
    '채용·인턴',
    '특강·교육',
    '국제교류',
    '봉사',
    '생활·시설',
    '시스템',
    '기타',
  ],
  tags: [
    '개발',
    'AI·데이터',
    '디자인',
    '영상·콘텐츠',
    '마케팅·홍보',
    '기획·창업',
    '글쓰기',
    '외국어·글로벌',
    '금융·경제',
    '공공·정책',
    '환경·사회',
    '봉사',
    '연구',
    '스포츠·문화',
  ],
  profileFields: {
    name: '이름',
    phone: '연락처',
    email: '이메일',
    studentId: '학번',
    school: '학교',
    major: '학과',
    year: '학년',
    birthDate: '생년월일',
    portfolioUrl: '포트폴리오 링크',
    certificates: '자격증',
    awards: '수상',
    activities: '활동',
  },
};
