export const config = {
  apiBase: '/api',
  demoBase: '/mock',
  demoQueryKey: 'demo',
  upcomingDays: 7,
  noticeGroups: [
    {
      id: 'sw-college',
      label: '국민대 SW대학',
      icon: 'document',
      sources: ['cs.kookmin.ac.kr', 'SW대학', '소프트웨어융합대학', '소프트웨어대학'],
    },
    {
      id: 'sw-project',
      label: 'SW사업단',
      icon: 'sparkles',
      sources: ['SW사업단', '소프트웨어중심대학', 'SW중심대학', 'SW교육센터'],
    },
    {
      id: 'competition',
      label: '공모전',
      icon: 'sparkles',
      categories: ['공모전·행사'],
      keywords: ['공모전', '경진대회'],
      exclude: ['서포터즈', '홍보대사', '대외활동', '기자단'],
    },
    {
      id: 'volunteer',
      label: '봉사활동',
      icon: 'check-circle',
      categories: ['봉사'],
      keywords: ['봉사활동', '봉사단'],
    },
    {
      id: 'activity',
      label: '대외활동',
      icon: 'arrow-up-right',
      keywords: ['대외활동', '서포터즈', '홍보대사', '기자단'],
    },
    {
      id: 'scholarship',
      label: '장학',
      icon: 'shield',
      categories: ['장학'],
      keywords: ['장학금', '장학생'],
    },
    {
      id: 'career',
      label: '취업·인턴',
      icon: 'document',
      categories: ['채용·인턴'],
      keywords: ['인턴', '채용'],
    },
    { id: 'education', label: '학사·교육', icon: 'document', categories: ['학사', '특강·교육'] },
    { id: 'global', label: '국제교류', icon: 'arrow-up-right', categories: ['국제교류'] },
    { id: 'other', label: '기타 소식', icon: 'document' },
  ],
  searchAliases: [
    { terms: ['소프트웨어융합대학', '소프트웨어대학'], replacement: 'sw대학' },
    {
      terms: ['소프트웨어중심대학사업단', 'sw중심대학사업단', '소프트웨어중심대학', 'sw중심대학'],
      replacement: 'sw사업단',
    },
    { terms: ['국민대학교'], replacement: '국민대' },
  ],
  profileKey: 'kmu.profile',
  sessionKey: 'kmu.session',
  timeZone: 'Asia/Seoul',
  categories: [
    '학사',
    '장학',
    '공모전·행사',
    '채용·인턴',
    '특강·교육',
    '국제교류',
    '봉사',
    '생활·시설',
    '시스템',
    '기타',
  ],
  tags: [
    '개발',
    'AI·데이터',
    '디자인',
    '영상·콘텐츠',
    '마케팅·홍보',
    '기획·창업',
    '글쓰기',
    '외국어·글로벌',
    '금융·경제',
    '공공·정책',
    '환경·사회',
    '봉사',
    '연구',
    '스포츠·문화',
  ],
  profileFields: {
    name: '이름',
    phone: '연락처',
    email: '이메일',
    studentId: '학번',
    school: '학교',
    major: '학과',
    year: '학년',
    birthDate: '생년월일',
    portfolioUrl: '포트폴리오 링크',
    certificates: '자격증',
    awards: '수상',
    activities: '활동',
  },
};
