export const config = {
  // 상대 경로: /proxy/{포트}/ 같은 하위 경로 뒤에서도 같은 출처로 동작한다
  apiBase: './api',
  demoBase: './mock',
  demoQueryKey: 'demo',
  profileKey: 'kmu.profile',
  sessionKey: 'kmu.session',
  timeZone: 'Asia/Seoul',
  // 백엔드 분류 (GET /api/categories)
  categories: ['학사·생활', '졸업', '장학', '취업', '행사·대외활동', '기타'],
  // 더미 미리보기(?demo=1) 자료가 쓰는 PRD v0.4 분류
  demoCategories: [
    '학사',
    '공모전·행사',
    '채용·인턴',
    '특강·교육',
    '국제교류',
    '봉사',
    '생활·시설',
    '시스템',
  ],
  tags: [
    '개발',
    'AI·데이터',
    '디자인',
    '영상·콘텐츠',
    '마케팅·홍보',
    '기획·창업',
    '글쓰기',
    '외국어·글로벌',
    '금융·경제',
    '공공·정책',
    '환경·사회',
    '봉사',
    '연구',
    '스포츠·문화',
  ],
  profileFields: {
    name: '이름',
    phone: '연락처',
    email: '이메일',
    studentId: '학번',
    school: '학교',
    major: '학과',
    year: '학년',
    birthDate: '생년월일',
    portfolioUrl: '포트폴리오 링크',
    certificates: '자격증',
    awards: '수상',
    activities: '활동',
  },
};
